### ISSUE TITLE
[CI]tempest测试用例失败--HybridVCloudServerPersonalityTestJSON.test_can_create_server_with_max_number_personality_files

### ISSUE THREAD

**Issue by liulongzhu** [Hybrid-Cloud/hybrid_cloud#57]
失败用例为：
compute.servers.test_servers_operations.HybridVCloudServerPersonalityTestJSON.test_can_create_server_with_max_number_personality_files
错误信息如下：
2016-05-20 00:19:19,879 12447 INFO     [tempest.lib.common.ssh] Creating ssh connection to '162.3.253.183' as 'root' with public key authentication
2016-05-20 00:20:19,885 12447 WARNING  [tempest.lib.common.ssh] Failed to establish authenticated ssh connection to root@162.3.253.183 (timed out). Number attempts: 1. Retry after 2 seconds.
2016-05-20 00:21:22,421 12447 WARNING  [tempest.lib.common.ssh] Failed to establish authenticated ssh connection to root@162.3.253.183 (timed out). Number attempts: 2. Retry after 3 seconds.
2016-05-20 00:22:25,982 12447 WARNING  [tempest.lib.common.ssh] Failed to establish authenticated ssh connection to root@162.3.253.183 (timed out). Number attempts: 3. Retry after 4 seconds.
2016-05-20 00:23:30,532 12447 WARNING  [tempest.lib.common.ssh] Failed to establish authenticated ssh connection to root@162.3.253.183 (timed out). Number attempts: 4. Retry after 5 seconds.
2016-05-20 00:24:36,045 12447 ERROR    [tempest.lib.common.ssh] Failed to establish authenticated ssh connection to root@162.3.253.183 after 4 attempts
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh Traceback (most recent call last):
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh   File "/opt/hybrid_cloud_test/tempest_jacket/tempest/lib/common/ssh.py", line 75, in _get_ssh_connection
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh     timeout=self.channel_timeout, pkey=self.pkey)
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh   File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 292, in connect
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh     retry_on_signal(lambda: sock.connect(addr))
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh   File "/usr/local/lib/python2.7/dist-packages/paramiko/util.py", line 270, in retry_on_signal
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh     return function()
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh   File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 292, in <lambda>
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh     retry_on_signal(lambda: sock.connect(addr))
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh   File "/usr/lib/python2.7/socket.py", line 224, in meth
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh     return getattr(self._sock,name)(*args)
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh timeout: timed out
2016-05-20 00:24:36.045 12447 ERROR tempest.lib.common.ssh

**Comment by liulongzhu** [comment]
同issue 66，与https://github.com/Hybrid-Cloud/hybrid_cloud/issues/57合并
